language: node_js
sudo: false
node_js:
  - "0.12"
before_install: npm install -g grunt-cli
install: npm install
script: grunt default --verbose
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "canal.min.js"
  skip_cleanup: true
  overwrite: true