language: node_js
os:
  - linux
dist: xenial
node_js:
  - "18"
  - "17"
  - "8"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run test
  - npm run report
  - npm run build
